### PR TITLE
Implement type-level time zone labels

### PR DESCRIPTION
**Pull request by enzoh**

### CODE REVIEW

**Comment by klao** [comment]
Hi Enzo,

Thanks a lot! A quick question: other than looking cool, do you have a use-case in mind for this? Something like preventing a possible class of bugs, or?..

I don't have anything against it, and will try to take a look as soon as I can! I'm just interested, why did you implement this, just because we can, or you want it for something. :)

Mihaly

**Comment by enzoh** [comment]
Hi Mihaly,

Thanks for the quick reply. I have timestamp types that depend on time zone values, including a UTC offset value, a daylight savings time value, an abbreviation value, and your time zone label value. These parameterizations are type-checked by GHC at compile-time, and that helps prevent timestamps from being misconstrued by programmers. Sometimes the parameterizations are unknown at compile-time and must be promoted to the type-level at run-time via proxy. This is the case when you are reading time zone values in from a file or off the wire. My pull request provides some utilities for dealing with this. Thanks for your consideration.

Warm regards,

Enzo

**Comment by enzoh** [comment]
Do you have a time estimate for when this will be merged?

**Comment by klao** [comment]
Thanks again, Enzo!

I have a few comments/questions:
1. I am not sure what is your test case supposed to test. It doesn't test the consistency of `KnownTZLabel` / `someTZLabelVal`. (Try to change one instance definition or one right-hand-side to break it.)  I guess it tests the correctness of `promoteTZLabel`, but it is so constrained by the type and simple...  I added a test to check the consistency of instances/cases, check it out. What did you have in mind with that test?
2. Redundant constraint warning for `promoteTZLabel`. I don't like warnings. :)  Do you have an idea for this? Or should we just suppress this warning in this file?
3. GADTs vs ExistentialQuantification. I very much prefer GADTs, I find the definitions much easier to read that way. Do you mind if I change `SomeTZLabel` definition to GADT style?

**Comment by klao** [comment]
Released to Hackage

**Pull request merged**
