### PR TITLE
Update to 2020c

### PR DESCRIPTION
**Pull request by phadej**
tzcode.patch doesn't apply cleanly, so I just removed it,
and it worked well on my machine without it.

Change nameToLabel to replace + to ' and not empty string,
this is due Etc-GMT+0 and Etc-GMT0 timezones (also new `Root_` timezones), which would map to the
same otherwise.

Make tzdata to not `wget` if files are locally.
(My internet is sometimes flaky)

---

This change should technically require `0.2` i.e. major bump version as the `TZLabel` is changed. I don't know what you have done previously, and whether its really an issue. OTOH, the `` -> `'` change might actually break someone.

```diff
++ Africa__Addis_Ababa :: TZLabel
++ Africa__Asmara :: TZLabel
++ Africa__Asmera :: TZLabel
++ Africa__Bamako :: TZLabel
++ Africa__Bangui :: TZLabel
++ Africa__Banjul :: TZLabel
++ Africa__Blantyre :: TZLabel
++ Africa__Brazzaville :: TZLabel
++ Africa__Bujumbura :: TZLabel
++ Africa__Conakry :: TZLabel
++ Africa__Dakar :: TZLabel
++ Africa__Dar_es_Salaam :: TZLabel
++ Africa__Djibouti :: TZLabel
++ Africa__Douala :: TZLabel
++ Africa__Freetown :: TZLabel
++ Africa__Gaborone :: TZLabel
++ Africa__Harare :: TZLabel
++ Africa__Kampala :: TZLabel
++ Africa__Kigali :: TZLabel
++ Africa__Kinshasa :: TZLabel
++ Africa__Libreville :: TZLabel
++ Africa__Lome :: TZLabel
++ Africa__Luanda :: TZLabel
++ Africa__Lubumbashi :: TZLabel
++ Africa__Lusaka :: TZLabel
++ Africa__Malabo :: TZLabel
++ Africa__Maseru :: TZLabel
++ Africa__Mbabane :: TZLabel
++ Africa__Mogadishu :: TZLabel
++ Africa__Niamey :: TZLabel
++ Africa__Nouakchott :: TZLabel
++ Africa__Ouagadougou :: TZLabel
++ Africa__Porto_Novo :: TZLabel
++ Africa__Timbuktu :: TZLabel
++ America__Anguilla :: TZLabel
++ America__Antigua :: TZLabel
++ America__Argentina__ComodRivadavia :: TZLabel
++ America__Aruba :: TZLabel
++ America__Atka :: TZLabel
++ America__Buenos_Aires :: TZLabel
++ America__Catamarca :: TZLabel
++ America__Cayman :: TZLabel
++ America__Coral_Harbour :: TZLabel
++ America__Cordoba :: TZLabel
++ America__Dominica :: TZLabel
++ America__Ensenada :: TZLabel
++ America__Fort_Wayne :: TZLabel
++ America__Grenada :: TZLabel
++ America__Guadeloupe :: TZLabel
++ America__Indianapolis :: TZLabel
++ America__Jujuy :: TZLabel
++ America__Knox_IN :: TZLabel
++ America__Kralendijk :: TZLabel
++ America__Louisville :: TZLabel
++ America__Lower_Princes :: TZLabel
++ America__Marigot :: TZLabel
++ America__Mendoza :: TZLabel
++ America__Montreal :: TZLabel
++ America__Montserrat :: TZLabel
++ America__Nuuk :: TZLabel
++ America__Porto_Acre :: TZLabel
++ America__Rosario :: TZLabel
++ America__Santa_Isabel :: TZLabel
++ America__Shiprock :: TZLabel
++ America__St_Barthelemy :: TZLabel
++ America__St_Kitts :: TZLabel
++ America__St_Lucia :: TZLabel
++ America__St_Thomas :: TZLabel
++ America__St_Vincent :: TZLabel
++ America__Tortola :: TZLabel
++ America__Virgin :: TZLabel
++ Antarctica__McMurdo :: TZLabel
++ Antarctica__South_Pole :: TZLabel
++ Arctic__Longyearbyen :: TZLabel
++ Asia__Aden :: TZLabel
++ Asia__Ashkhabad :: TZLabel
++ Asia__Bahrain :: TZLabel
++ Asia__Calcutta :: TZLabel
++ Asia__Chongqing :: TZLabel
++ Asia__Chungking :: TZLabel
++ Asia__Dacca :: TZLabel
++ Asia__Harbin :: TZLabel
++ Asia__Istanbul :: TZLabel
++ Asia__Kashgar :: TZLabel
++ Asia__Katmandu :: TZLabel
++ Asia__Kuwait :: TZLabel
++ Asia__Macao :: TZLabel
++ Asia__Muscat :: TZLabel
++ Asia__Phnom_Penh :: TZLabel
++ Asia__Rangoon :: TZLabel
++ Asia__Saigon :: TZLabel
++ Asia__Tel_Aviv :: TZLabel
++ Asia__Thimbu :: TZLabel
++ Asia__Ujung_Pandang :: TZLabel
++ Asia__Ulan_Bator :: TZLabel
++ Asia__Vientiane :: TZLabel
++ Atlantic__Faeroe :: TZLabel
++ Atlantic__Jan_Mayen :: TZLabel
++ Atlantic__St_Helena :: TZLabel
++ Australia__ACT :: TZLabel
++ Australia__Canberra :: TZLabel
++ Australia__LHI :: TZLabel
++ Australia__NSW :: TZLabel
++ Australia__North :: TZLabel
++ Australia__Queensland :: TZLabel
++ Australia__South :: TZLabel
++ Australia__Tasmania :: TZLabel
++ Australia__Victoria :: TZLabel
++ Australia__West :: TZLabel
++ Australia__Yancowinna :: TZLabel
++ Brazil__Acre :: TZLabel
++ Brazil__DeNoronha :: TZLabel
++ Brazil__East :: TZLabel
++ Brazil__West :: TZLabel
++ Canada__Atlantic :: TZLabel
++ Canada__Central :: TZLabel
++ Canada__Eastern :: TZLabel
++ Canada__Mountain :: TZLabel
++ Canada__Newfoundland :: TZLabel
++ Canada__Pacific :: TZLabel
++ Canada__Saskatchewan :: TZLabel
++ Canada__Yukon :: TZLabel
++ Chile__Continental :: TZLabel
++ Chile__EasterIsland :: TZLabel
++ Etc__GMT'0 :: TZLabel
++ Etc__GMT'1 :: TZLabel
++ Etc__GMT'10 :: TZLabel
++ Etc__GMT'11 :: TZLabel
++ Etc__GMT'12 :: TZLabel
++ Etc__GMT'2 :: TZLabel
++ Etc__GMT'3 :: TZLabel
++ Etc__GMT'4 :: TZLabel
++ Etc__GMT'5 :: TZLabel
++ Etc__GMT'6 :: TZLabel
++ Etc__GMT'7 :: TZLabel
++ Etc__GMT'8 :: TZLabel
++ Etc__GMT'9 :: TZLabel
++ Etc__GMT0 :: TZLabel
-- Etc__GMT1 :: TZLabel
-- Etc__GMT10 :: TZLabel
-- Etc__GMT11 :: TZLabel
-- Etc__GMT12 :: TZLabel
-- Etc__GMT2 :: TZLabel
-- Etc__GMT3 :: TZLabel
-- Etc__GMT4 :: TZLabel
-- Etc__GMT5 :: TZLabel
-- Etc__GMT6 :: TZLabel
-- Etc__GMT7 :: TZLabel
-- Etc__GMT8 :: TZLabel
-- Etc__GMT9 :: TZLabel
++ Etc__GMT_0 :: TZLabel
++ Etc__Greenwich :: TZLabel
++ Etc__UCT :: TZLabel
++ Etc__Universal :: TZLabel
++ Etc__Zulu :: TZLabel
++ Europe__Belfast :: TZLabel
++ Europe__Bratislava :: TZLabel
++ Europe__Busingen :: TZLabel
++ Europe__Guernsey :: TZLabel
++ Europe__Isle_of_Man :: TZLabel
++ Europe__Jersey :: TZLabel
++ Europe__Ljubljana :: TZLabel
++ Europe__Mariehamn :: TZLabel
++ Europe__Nicosia :: TZLabel
++ Europe__Podgorica :: TZLabel
++ Europe__San_Marino :: TZLabel
++ Europe__Sarajevo :: TZLabel
++ Europe__Skopje :: TZLabel
++ Europe__Tiraspol :: TZLabel
++ Europe__Vaduz :: TZLabel
++ Europe__Vatican :: TZLabel
++ Europe__Zagreb :: TZLabel
++ Indian__Antananarivo :: TZLabel
++ Indian__Comoro :: TZLabel
++ Indian__Mayotte :: TZLabel
++ Mexico__BajaNorte :: TZLabel
++ Mexico__BajaSur :: TZLabel
++ Mexico__General :: TZLabel
++ Pacific__Johnston :: TZLabel
++ Pacific__Midway :: TZLabel
++ Pacific__Ponape :: TZLabel
++ Pacific__Saipan :: TZLabel
++ Pacific__Samoa :: TZLabel
++ Pacific__Truk :: TZLabel
++ Pacific__Yap :: TZLabel
++ Root__Cuba :: TZLabel
++ Root__Egypt :: TZLabel
++ Root__Eire :: TZLabel
++ Root__GB :: TZLabel
++ Root__GB_Eire :: TZLabel
++ Root__GMT :: TZLabel
++ Root__GMT'0 :: TZLabel
++ Root__GMT0 :: TZLabel
++ Root__GMT_0 :: TZLabel
++ Root__Greenwich :: TZLabel
++ Root__Hongkong :: TZLabel
++ Root__Iceland :: TZLabel
++ Root__Iran :: TZLabel
++ Root__Israel :: TZLabel
++ Root__Jamaica :: TZLabel
++ Root__Japan :: TZLabel
++ Root__Kwajalein :: TZLabel
++ Root__Libya :: TZLabel
++ Root__NZ :: TZLabel
++ Root__NZ_CHAT :: TZLabel
++ Root__Navajo :: TZLabel
++ Root__PRC :: TZLabel
++ Root__Poland :: TZLabel
++ Root__Portugal :: TZLabel
++ Root__ROC :: TZLabel
++ Root__ROK :: TZLabel
++ Root__Singapore :: TZLabel
++ Root__Turkey :: TZLabel
++ Root__UCT :: TZLabel
++ Root__UTC :: TZLabel
++ Root__Universal :: TZLabel
++ Root__W_SU :: TZLabel
++ Root__Zulu :: TZLabel
++ US__Alaska :: TZLabel
++ US__Aleutian :: TZLabel
++ US__Arizona :: TZLabel
++ US__Central :: TZLabel
++ US__East_Indiana :: TZLabel
++ US__Eastern :: TZLabel
++ US__Hawaii :: TZLabel
++ US__Indiana_Starke :: TZLabel
++ US__Michigan :: TZLabel
++ US__Mountain :: TZLabel
++ US__Pacific :: TZLabel
++ US__Samoa :: TZLabel
```

### CODE REVIEW

**Comment by phadej** [comment]
2020c version was released, so I added it here. 

```
The 2020c release of the tz code and data is available. It reflects the following changes, which were either circulated on the tz mailing list or are relatively minor technical or administrative changes:

  Briefly:
    Fiji starts DST later than usual, on 2020-12-20.

  Changes to future timestamps

    Fiji will start DST on 2020-12-20, instead of 2020-11-08 as
    previously predicted.  DST will still end on 2021-01-17.
    (Thanks to Raymond Kumar and Alan Mintz.)  Assume for now that
    the later-than-usual start date is a one-time departure from the
    recent pattern. 
```

**Comment by phadej** [comment]
The release notes mention

> If your tzdata parser does not yet support negative DST offsets or times past 24:00 ...

Nothing broke during generation nor compliation, but I'm not 100% sure there's nothing wrong going on.

**Comment by klao** [comment]
Sorry for letting this slip. I'll fix the tests and then release.

> The release notes mention
> 
> > If your tzdata parser does not yet support negative DST offsets or times past 24:00 ...
> 
> Nothing broke during generation nor compliation, but I'm not 100% sure there's nothing wrong going on.

That's more for the `tz` package to worry about, I'll check it later.

**Comment by phadej** [comment]
No worries, I'm quite happy making these small PRs as I notice IANA announcements :)

**Comment by klao** [comment]
Uploaded `0.2.20201016.0` to Hackage.

Thanks again for all the help!

**Pull request merged**
